### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by 943fansi** [xiang-deng/papers#1]
It looks like you read a lot of papers, any paper recommendations on time series anomaly detection?

**Comment by xiang-deng** [comment]
Hi, thanks for your interest. Actually, this is just a test repo I used to automatically process my Google Scholar Alerts and generate RSS feeds that I can check on my phone. You could try to set alerts with your interests of keywords/researcher on google scholar. Semantic scholar also has similar feature.
